name: auth_api
description: Concrete API implementation of the AuthClient interface.
repository: https://github.com/flutter-news-app-full-source-code/auth-api
publish_to: none
version: 1.0.1

environment:
  sdk: ^3.9.0

dependencies:
  auth_client:
    git:
      url: https://github.com/flutter-news-app-full-source-code/auth-client.git
      ref: v1.0.1
  core:
    git:
      url: https://github.com/flutter-news-app-full-source-code/core.git
      ref: v1.3.1
  http_client:
    git:
      url: https://github.com/flutter-news-app-full-source-code/http-client.git
      ref: v1.0.1
  logging: ^1.3.0

dev_dependencies:
  mocktail: ^1.0.4
  test: ^1.25.8
  very_good_analysis: ^10.1.0
